Kp = 0.00068;
Ki = 0.01;
Kd = 1.203e-06;

T = .01;

% Stuff to plug into C program.
P = Kp;
A0 = Kp + (Ki*T/2) + (Kd/T);
A1 = Kp + (Kd/T) - (Ki*T/2) + (Kd/T);
A2 = (Kd/T);

scale = 2^20

result = sprintf(['\n***************************\n', ...
                  '* Den    :  %12.4f  *\n'   ...
                  '* A0     :  %12.4f  *\n',  ...
                  '* A1     :  %12.4f  *\n',  ...
                  '* A2     :  %12.4f  *\n',  ...
                  '* A0_inv :  %12.4f  *\n',  ...
                  '* A1_inv :  %12.4f  *\n',  ...
                  '* A2_inv :  %12.4f  *\n',  ...
                  '***************************\n'], ...
                 scale, scale*A0, scale*A1, scale*A2, ...
                 1/(scale*A0), 1/(scale*A1), 1/(scale*A2));
              
disp(result);